version: '3'
services:

  ################################################
  ## Local Sites Setup:                         ##
  ## Nginx, Elastic Search, Redis               ##
  ################################################
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - clay
    networks:
      main:
        aliases:
          - clay.radio.com
    ports:
      - "80:80"

  clay:
    build:
      context: ./app
      dockerfile: Dockerfile
    logging:
      driver: json-file
    depends_on:
      - elasticsearch
    links:
      - redis
      - elasticsearch
      - postgres
    networks:
      main:
    command: "npm run dev"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: redis
    logging:
      driver: none
    networks:
      main:
    ports:
      - "6379:6379"
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    command: elasticsearch
    logging:
      driver: none
    networks:
      main:
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  postgres:
    image: postgres:10.4
    networks:
      main:
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  main:
