{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "clay-radio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "clay-radio.name" . }}
    helm.sh/chart: {{ include "clay-radio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: clay-radio
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clay-radio.name" . }}
{{ end }}
